import { type NextRequest, NextResponse } from "next/server"

// Expanded sample titles for random images (200+ titles)
const imageTitles = [
  "Serene Mountain Landscape",
  "Urban City Skyline",
  "Peaceful Ocean Waves",
  "Vibrant Sunset Colors",
  "Misty Forest Path",
  "Desert Sand Dunes",
  "Blooming Spring Flowers",
  "Starry Night Sky",
  "Rustic Countryside",
  "Modern Architecture",
  "Tropical Beach Paradise",
  "Snow-Capped Peaks",
  "Autumn Leaves Falling",
  "Bustling Street Market",
  "Calm Lake Reflection",
  "Dramatic Storm Clouds",
  "Colorful Street Art",
  "Ancient Stone Bridge",
  "Golden Hour Meadow",
  "Crystal Clear Waterfall",
  "Majestic Eagle Soaring",
  "Cozy Coffee Shop",
  "Neon City Lights",
  "Peaceful Garden Path",
  "Vintage Car Collection",
  "Lighthouse on Cliff",
  "Butterfly on Flower",
  "Snowy Pine Forest",
  "Abstract Geometric Patterns",
  "Rustic Barn Door",
  "Ocean Sunset Silhouette",
  "Mountain Lake Mirror",
  "Urban Graffiti Wall",
  "Wildflower Field",
  "Gothic Cathedral",
  "Modern Glass Building",
  "Desert Cactus Bloom",
  "Foggy Morning Landscape",
  "Colorful Hot Air Balloons",
  "Ancient Ruins",
  "Peaceful Zen Garden",
  "Stormy Ocean Waves",
  "Cherry Blossom Tree",
  "Industrial Cityscape",
  "Tropical Rainforest",
  "Vintage Bookshelf",
  "Minimalist Interior",
  "Dramatic Mountain Range",
  "Street Food Vendor",
  "Elegant Swan Lake",
  "Rustic Wooden Dock",
  "Vibrant Market Stall",
  "Moonlit Forest Path",
  "Modern Art Gallery",
  "Coastal Cliff View",
  "Autumn Forest Trail",
  "Urban Rooftop Garden",
  "Vintage Train Station",
  "Peaceful Monastery",
  "Colorful Coral Reef",
  "Snow-Covered Village",
  "Abstract Light Patterns",
  "Rustic Farm Landscape",
  "City Bridge at Night",
  "Tropical Fish Swimming",
  "Gothic Architecture Detail",
  "Modern Sculpture Park",
  "Desert Sunrise",
  "Peaceful River Bend",
  "Urban Street Photography",
  "Mountain Hiking Trail",
  "Vintage Market Square",
  "Colorful Butterfly Garden",
  "Dramatic Sky Formation",
  "Rustic Stone Cottage",
  "Modern City Plaza",
  "Tropical Island View",
  "Ancient Temple Ruins",
  "Peaceful Lakeside Cabin",
  "Urban Art Installation",
  "Mountain Valley Vista",
  "Vintage Lighthouse",
  "Colorful Flower Market",
  "Dramatic Waterfall",
  "Rustic Country Road",
  "Modern Skyscraper",
  "Tropical Sunset Beach",
  "Ancient Castle Walls",
  "Peaceful Meditation Space",
  "Urban Night Market",
  "Mountain Peak Sunrise",
  "Vintage Cafe Interior",
  "Colorful Street Festival",
  "Dramatic Cloud Formation",
  "Rustic Windmill",
  "Modern Bridge Design",
  "Tropical Jungle Path",
  "Ancient Stone Circle",
  "Peaceful Garden Pond",
  "Urban Skyline Reflection",
  "Mountain Forest Canopy",
  "Vintage Library Interior",
  "Colorful Mosaic Art",
  "Dramatic Seascape",
  "Rustic Farmhouse",
  "Modern Art Museum",
  "Tropical Bird Paradise",
  "Ancient Amphitheater",
  "Peaceful Mountain Stream",
  "Urban Food Market",
  "Desert Rock Formation",
  "Vintage Clock Tower",
  "Colorful Kite Festival",
  "Dramatic Lightning Storm",
  "Rustic Covered Bridge",
  "Modern Glass Facade",
  "Tropical Waterfall Pool",
  "Ancient Monastery",
  "Peaceful Countryside",
  "Urban Bike Path",
  "Mountain Glacier View",
  "Vintage Antique Shop",
  "Colorful Carnival Ride",
  "Dramatic Sunset Silhouette",
  "Rustic Log Cabin",
  "Modern Sculpture Garden",
  "Tropical Palm Grove",
  "Ancient Pyramid",
  "Peaceful Bamboo Forest",
  "Urban Rooftop View",
  "Mountain Alpine Lake",
  "Vintage Record Store",
  "Colorful Graffiti Mural",
  "Dramatic Ocean Storm",
  "Rustic Stone Wall",
  "Modern Architecture Detail",
  "Tropical Coral Garden",
  "Ancient Roman Ruins",
  "Peaceful Meadow Stream",
  "Urban Night Photography",
  "Mountain Snow Field",
  "Vintage Bookstore",
  "Colorful Lantern Festival",
  "Dramatic Cliff Edge",
  "Rustic Wooden Bridge",
  "Modern City Park",
  "Tropical Beach Hammock",
  "Ancient Greek Temple",
  "Peaceful Forest Clearing",
  "Urban Street Art",
  "Mountain Hiking Path",
  "Vintage Tea Shop",
  "Colorful Flower Garden",
  "Dramatic Storm Approaching",
  "Rustic Country Church",
  "Modern Glass Tower",
  "Tropical Island Lagoon",
  "Ancient Stone Bridge",
  "Peaceful River Valley",
  "Urban Market Scene",
  "Mountain Peak Reflection",
  "Vintage Train Car",
  "Colorful Butterfly House",
  "Dramatic Seashore",
  "Rustic Barn Interior",
  "Modern Art Installation",
  "Tropical Fish Market",
  "Ancient Castle Tower",
  "Peaceful Garden Pathway",
  "Urban Rooftop Terrace",
  "Mountain Forest Stream",
  "Vintage Pharmacy",
  "Colorful Street Musician",
  "Dramatic Sky Panorama",
  "Rustic Stone Cottage",
  "Modern Bridge Span",
  "Tropical Sunset Cruise",
  "Ancient Temple Complex",
  "Peaceful Lake Dock",
  "Urban Food Truck",
  "Mountain Valley Floor",
  "Vintage Barber Shop",
  "Colorful Market Produce",
  "Dramatic Coastal View",
  "Rustic Farm Equipment",
  "Modern City Square",
  "Tropical Beach Resort",
  "Ancient Fortress Wall",
  "Peaceful Garden Bench",
  "Urban Street Corner",
  "Mountain Trail Marker",
  "Vintage Music Store",
  "Colorful Festival Lights",
  "Dramatic Weather Front",
  "Rustic Country Gate",
  "Modern Office Building",
  "Tropical Diving Spot",
  "Ancient Burial Ground",
  "Peaceful Pond Reflection",
  "Urban Bike Lane",
  "Mountain Cabin View",
  "Vintage Jewelry Shop",
  "Colorful Parade Float",
  "Dramatic Sunrise Colors",
  "Rustic Wooden Fence",
  "Modern Shopping Center",
  "Tropical Bird Watching",
  "Ancient Stone Carving",
  "Peaceful Garden Statue",
  "Urban Pedestrian Zone",
  "Mountain Overlook Point",
  "Vintage Toy Store",
  "Colorful Art Exhibition",
  "Dramatic Cloud Burst",
  "Rustic Mill Wheel",
  "Modern Convention Center",
  "Tropical Snorkeling Area",
  "Ancient Aqueduct",
  "Peaceful Riverside Walk",
  "Urban Food Court",
  "Mountain Ski Slope",
  "Vintage Flower Shop",
  "Colorful Dance Performance",
  "Dramatic Tidal Pool",
  "Rustic Picket Fence",
  "Modern Sports Stadium",
  "Tropical Fishing Village",
  "Ancient Observatory",
  "Peaceful Garden Fountain",
  "Urban Shopping District",
  "Mountain Camping Site",
  "Vintage Bakery",
  "Colorful Craft Fair",
  "Dramatic Rock Formation",
  "Rustic Water Mill",
  "Modern Transportation Hub",
]

// Expanded image categories
const imageCategories = [
  "nature",
  "city",
  "landscape",
  "architecture",
  "travel",
  "food",
  "technology",
  "animals",
  "abstract",
  "people",
  "ocean",
  "mountains",
  "forest",
  "desert",
  "flowers",
  "sunset",
  "vintage",
  "modern",
  "art",
  "street",
  "buildings",
  "water",
  "sky",
  "wildlife",
  "urban",
  "rural",
  "tropical",
  "winter",
  "spring",
  "summer",
  "autumn",
  "night",
  "morning",
  "evening",
  "dramatic",
  "peaceful",
  "colorful",
  "minimalist",
  "rustic",
  "contemporary",
  "historical",
  "cultural",
  "scenic",
  "adventure",
  "relaxation",
]

function getRandomElement<T>(array: T[]): T {
  return array[Math.floor(Math.random() * array.length)]
}

function generateRandomImage(index = 0) {
  const width = 800
  const height = 600
  const category = getRandomElement(imageCategories)
  const title = getRandomElement(imageTitles)

  // Use different image services for variety with unique seeds
  const seed = Math.floor(Math.random() * 10000) + index
  const imageServices = [
    `https://picsum.photos/${width}/${height}?random=${seed}`,
    `https://source.unsplash.com/${width}x${height}/?${category}&sig=${seed}`,
    `https://picsum.photos/${width}/${height}?blur=1&random=${seed + 1000}`,
    `https://source.unsplash.com/${width}x${height}/?${category}&orientation=landscape&sig=${seed + 2000}`,
  ]

  const imageUrl = getRandomElement(imageServices)

  return {
    id: `img_${Date.now()}_${Math.random().toString(36).substr(2, 9)}_${index}`,
    title,
    image: imageUrl,
    category,
    timestamp: new Date().toISOString(),
  }
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const count = Number.parseInt(searchParams.get("count") || "1")
    const category = searchParams.get("category")
    const offset = Number.parseInt(searchParams.get("offset") || "0")

    // Increased limit to 1000 images
    const imageCount = Math.min(Math.max(count, 1), 1000)

    const images = []

    // Generate images with better performance for large requests
    for (let i = 0; i < imageCount; i++) {
      const image = generateRandomImage(i + offset)

      // If category is specified, use it
      if (category && imageCategories.includes(category.toLowerCase())) {
        image.category = category.toLowerCase()
        image.image = `https://source.unsplash.com/800x600/?${category}&sig=${Date.now() + i + offset}`
      }

      images.push(image)
    }

    // Add pagination info for large requests
    const response = {
      success: true,
      count: images.length,
      offset: offset,
      total_requested: imageCount,
      data: imageCount === 1 ? images[0] : images,
    }

    // Add pagination metadata for requests > 50
    if (imageCount > 50) {
      response.pagination = {
        current_offset: offset,
        current_count: imageCount,
        next_offset: offset + imageCount,
        has_more: true, // Always true since we can generate infinite images
      }
    }

    return NextResponse.json(response)
  } catch (error) {
    return NextResponse.json(
      {
        success: false,
        error: "Failed to generate random images",
      },
      { status: 500 },
    )
  }
}
